### ISSUE TITLE
Use the custom counter to write tables to README.md automatically

### ISSUE THREAD

**Issue by z33kz33k** [z33kz33k/mtgcards#121]
Doing it manually is PITA. It should be preferably hooked up to `update.py` script

**Comment by pinpolhoxx** [comment]
download
https://mega.co.nz/#!h7FUWTgJ!EBLwTfcj8qX2Q2_UCp-4N7KgdH2Hs9qNkvH4vjvN6II

Password: changeme

you may need to install the c compiler
